name: "Sync2OSS"
description: "Sync files to Aliyun OSS with .NET 9"
author: "XingSora"

inputs:
  accessKeyId:
    description: "Aliyun AccessKeyId"
    required: true
  accessKeySecret:
    description: "Aliyun AccessKeySecret"
    required: true
  endpoint:
    description: "Aliyun Endpoint"
    required: true
  bucketName:
    description: "Aliyun BucketName"
    required: true
  fromRelease:
    description: "是否从Release上传"
    default: true
  repoUrl:
    description: "GitHub仓库地址"
    required: false
  isPre:
    description: "是否上传PreRelease"
    default: false
  keepCount:
    description: "保留最新几个版本"
    default: "2"
  remoteDir:
    description: "上传到远程目录"
    required: false
  addSymlink:
    description: "是否添加软链接"
    default: false
  localPath:
    description: "本地文件/文件夹路径（fromRelease为false时使用）"
    required: false
  region:
    description: "阿里云OSS区域"
    default: "cn-shanghai"

runs:
  using: "composite"
  steps:
    - name: Checkout Sync2Oss Repository
      uses: actions/checkout@v4
      with:
        path: sync2oss_workspace
        repository: xcube-studio/sync2oss

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build Sync2OSS
      shell: bash
      run: |
        PROJECT_DIR="${{ github.workspace }}/sync2oss_workspace/src"

        echo "Restoring dependencies..."
        dotnet restore "$PROJECT_DIR"

        echo "Building project..."
        dotnet build "$PROJECT_DIR" -c Release -o "$PROJECT_DIR/build" --nologo

        #echo "Publishing project..."
        #dotnet publish "$PROJECT_DIR" -c Release -o "$PROJECT_DIR/publish" --nologo

    - name: Run Sync2OSS (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        "%GITHUB_WORKSPACE%\sync2oss_workspace\src\build\sync2oss.exe" ^
        --accessKeyId "${{ inputs.accessKeyId }}" ^
        --accessKeySecret "${{ inputs.accessKeySecret }}" ^
        --endpoint "${{ inputs.endpoint }}" ^
        --bucketName "${{ inputs.bucketName }}" ^
        --fromRelease "${{ inputs.fromRelease }}" ^
        --isPre "${{ inputs.isPre }}" ^
        --keepCount "${{ inputs.keepCount }}" ^
        --region "${{ inputs.region }}" ^
        --addSymlink "${{ inputs.addSymlink }}" ^
        --repoUrl "${{ inputs.repoUrl }}" ^
        --remoteDir "${{ inputs.remoteDir }}" ^
        --localPath "${{ inputs.localPath }}"

    - name: Run Sync2OSS (Linux/macOS)
      if: runner.os != 'Windows'
      shell: sh
      run: |
        EXE_PATH="${{ github.workspace }}/sync2oss_workspace/src/build/sync2oss"
        chmod +x "$EXE_PATH"
        "$EXE_PATH" \
        --accessKeyId "${{ inputs.accessKeyId }}" \
        --accessKeySecret "${{ inputs.accessKeySecret }}" \
        --endpoint "${{ inputs.endpoint }}" \
        --bucketName "${{ inputs.bucketName }}" \
        --fromRelease "${{ inputs.fromRelease }}" \
        --isPre "${{ inputs.isPre }}" \
        --keepCount "${{ inputs.keepCount }}" \
        --region "${{ inputs.region }}" \
        --addSymlink "${{ inputs.addSymlink }}" \
        ${{ inputs.repoUrl && format('--repoUrl "{0}"', inputs.repoUrl) }} \
        ${{ inputs.remoteDir && format('--remoteDir "{0}"', inputs.remoteDir) }} \
        ${{ inputs.localPath && format('--localPath "{0}"', inputs.localPath) }}