name: "Sync2OSS"
description: "Sync files to Aliyun OSS with .NET 8"
author: "XingSora"

inputs:
  accessKeyId:
    description: "Aliyun AccessKeyId"
    required: true
  accessKeySecret:
    description: "Aliyun AccessKeySecret"
    required: true
  endpoint:
    description: "Aliyun Endpoint"
    required: true
  bucketName:
    description: "Aliyun BucketName"
    required: true
  fromRelease:
    description: "是否从Release上传"
    default: "true"
  repoUrl:
    description: "GitHub仓库地址"
    required: false
  isPre:
    description: "是否上传PreRelease"
    default: "false"
  keepCount:
    description: "保留最新几个版本"
    default: "2"
  remoteDir:
    description: "上传到远程目录"
    required: false
  addSymlink:
    description: "是否添加软链接"
    default: false
  localPath:
    description: "本地文件/文件夹路径（fromRelease为false时使用）"
    required: false
  region:
    description: "阿里云OSS区域"
    default: "cn-shanghai"

runs:
  using: "composite"
  steps:
    - name: Checkout Sync2Oss Repository
      uses: actions/checkout@v4
      with:
        path: sync2oss_workspace
        repository: xcube-studio/sync2oss

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Sync2OSS
      shell: bash
      run: |
        PROJECT_DIR="${{ github.workspace }}/sync2oss_workspace/src"

        echo "Restoring dependencies..."
        dotnet restore "$PROJECT_DIR"

        echo "Building project..."
        dotnet build "$PROJECT_DIR" -c Release -o "$PROJECT_DIR/build" --nologo

        #echo "Publishing project..."
        #dotnet publish "$PROJECT_DIR" -c Release -o "$PROJECT_DIR/publish" --nologo

    - name: Run Sync2OSS
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          EXE_PATH="${{ github.workspace }}\sync2oss_workspace\src\build\sync2oss.exe"
        else
          EXE_PATH="${{ github.workspace }}/sync2oss_workspace/src/build/sync2oss"
        fi

        echo "Executable Path: $EXE_PATH"

        ARGS=(
          "--accessKeyId" "${{ inputs.accessKeyId }}"
          "--accessKeySecret" "${{ inputs.accessKeySecret }}"
          "--endpoint" "${{ inputs.endpoint }}"
          "--bucketName" "${{ inputs.bucketName }}"
          "--fromRelease" "${{ inputs.fromRelease }}"
          "--isPre" "${{ inputs.isPre }}"
          "--keepCount" "${{ inputs.keepCount }}"
          "--region" "${{ inputs.region }}"
          "--addSymlink" "${{ inputs.addSymlink }}"
        )

        [ -n "${{ inputs.repoUrl }}" ] && ARGS+=("--repoUrl" "${{ inputs.repoUrl }}")
        [ -n "${{ inputs.remoteDir }}" ] && ARGS+=("--remoteDir" "${{ inputs.remoteDir }}")
        [ -n "${{ inputs.localPath }}" ] && ARGS+=("--localPath" "${{ inputs.localPath }}")

        if [ -f "$EXE_PATH" ]; then
          "$EXE_PATH" "${ARGS[@]}"
          EXIT_CODE=$?  # 获取程序的退出码
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Error: The executable exited with code $EXIT_CODE"
            exit $EXIT_CODE  # 显式退出并将错误码传递给 GitHub Actions
          fi
        else
          echo "Error: Executable not found at $EXE_PATH"
          exit 1
        fi
